### ISSUE TITLE
Installation of fifer - add dependencies?

### ISSUE THREAD

**Issue by JanaJarecki** [dustinfife/fifer#4]
Hi,
Just FYI: Installing fifer via `install_github` R complains about missing packages (dependencies), maybe if there is time add those packages to the import list: 
- mice
- tidyverse
- cowplot
- lsmeans

The error is the usual

    Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
      there is no package called 'mice'

Cheerio,
Jana

PS: Maybe use patchwork (https://github.com/thomasp85/patchwork)  instead of cowplot, its a bit simpler I think ;) no offense if you deliberately decided against it.

**Comment by dustinfife** [comment]
Thanks, Jana. I've been procrastinating solving that one and I still don't quite now what the problem is. My namespace has all those in there, but for some reason, the error's still happening.

<img width="283" alt="screen shot 2018-11-15 at 12 21 23 pm" src="https://user-images.githubusercontent.com/7094676/48569924-0127e200-e8d1-11e8-8b0f-5496d131064c.png">

Based on some research, I suspect it might be problems with either the dependencies (mice, tidyverse, etc) or a dependency within those dependencies:

https://stackoverflow.com/questions/28887446/r-error-on-installing-colorspace-for-ggplot2
https://github.com/tidyverse/ggplot2/issues/540

In the mean time, you could always install those packages individually:

```
install.packages("mice")
install.packages("tidyverse")
install.packages("cowplot")
install.packages("lsmeans")
```
